//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Carts = new HashSet<Cart>();
            this.Certificates = new HashSet<Certificate>();
            this.Counselings = new HashSet<Counseling>();
            this.Ratings = new HashSet<Rating>();
            this.Transactions = new HashSet<Transaction>();
            this.ValidStudents = new HashSet<ValidStudent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public byte[] Photo { get; set; }
        public string Education { get; set; }
        public string Institution { get; set; }
        public string Password { get; set; }
        public string IsValid { get; set; }
        public string Gender { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<Certificate> Certificates { get; set; }
        public virtual ICollection<Counseling> Counselings { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<ValidStudent> ValidStudents { get; set; }
    }
}
